/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2023-03-18 18:07:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"favicon.ico\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- Font Awesome -->\r\n");
      out.write("\t<link\r\n");
      out.write("\t  href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\"\r\n");
      out.write("\t  rel=\"stylesheet\"\r\n");
      out.write("\t/>\r\n");
      out.write("\t<!-- Google Fonts -->\r\n");
      out.write("\t<link\r\n");
      out.write("\t  href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\"\r\n");
      out.write("\t  rel=\"stylesheet\"\r\n");
      out.write("\t/>\r\n");
      out.write("\t<link\r\n");
      out.write("\t  href=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.css\"\r\n");
      out.write("\t  rel=\"stylesheet\"\r\n");
      out.write("\t/>\r\n");
      out.write("\t<title>SomosNGR</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/login.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<section class=\"vh-100\">\r\n");
      out.write("  \t<div class=\"container-fluid p-0\">\r\n");
      out.write("    <div class=\"row-login vh-100 \">\r\n");
      out.write("\t   <div class=\"w-100 img-login  text-center\">\r\n");
      out.write("\t        <img src=\"./img/DSC_0005.webp\"\r\n");
      out.write("\t          alt=\"Login image\" class=\"w-100 vh-100\" style=\"object-fit: cover; object-position: center;\">\r\n");
      out.write("\t   </div>\r\n");
      out.write("      <div class=\"text-black\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"px-5 text-center mb-5\">\r\n");
      out.write("          <img alt=\"logo\" class=\"logo-app mt-4 mb-4  ng-lazyloaded\" src=\"./img/logo-somosngr.svg\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-flex align-items-center justify-content-center h-custom-2 px-5  mt-5 pt-5 pt-xl-0  \">\r\n");
      out.write("\r\n");
      out.write("          <form style=\"width: 20rem;\">\r\n");
      out.write("\r\n");
      out.write("            <h3 class=\"fw-normal mb-3 pb-3\" style=\"letter-spacing: 1px;\"></h3>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-outline mb-4\">\r\n");
      out.write("              <input type=\"email\" id=\"input-custom\" class=\"form-control form-control-lg \" />\r\n");
      out.write("              <label class=\"form-label\" for=\"form2Example18\">Número de Documento</label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-outline mb-5\">\r\n");
      out.write("              <input type=\"password\" id=\"input-custom\" class=\"form-control form-control-lg nput-custom\"\" />\r\n");
      out.write("              <label class=\"form-label\" for=\"form2Example28\">Contraseña</label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"pt-1 mb-4\">\r\n");
      out.write("              <button class=\"btn  btn-lg btn-block btn-login\" type=\"submit\">Ingresar</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"small mb-5 pb-lg-2\"><a class=\"text-muted\" href=\"#!\">Olvidé mi contraseña?</a></p>\r\n");
      out.write("            <p class=\"createNewLink\">Aún no tienes una cuenta?<a href=\"#!\" class=\"link-info\"> Registrarse Aqui!</a></p>\r\n");
      out.write("\r\n");
      out.write("          </form>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("  type=\"text/javascript\"\r\n");
      out.write("  src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.js\"\r\n");
      out.write("></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
