/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2023-04-05 16:26:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ListadoProveedores_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/E:/GitHubRepository/ProyectoLP-2023/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/proyectoLP_2023/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("jar:file:/E:/GitHubRepository/ProyectoLP-2023/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/proyectoLP_2023/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1679423164025L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- para dar formato a las fechas -->\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE >\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\" />\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link href=\"https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/dataTableGlobal.css\" />\r\n");
      out.write("\t\t<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("\t\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("\t\t<link href=\"https://fonts.googleapis.com/css2?family=Playball&display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("\t\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("\t\t<link href=\"https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,600;0,700;0,800;1,700&display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("\t\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("\t\t<link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/main.css\" />\r\n");
      out.write("\t\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\" />\r\n");
      out.write("\t\t<link href=\"https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link href=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.7.3/dist/sweetalert2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("\t\t<script src=\"https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(document).ready(function () {\r\n");
      out.write("\t\t\t    $('#data-table-basic').DataTable();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<title>Listado</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- ======= Header(Cabezera) ======= -->\r\n");
      out.write("\t\t<header id=\"header\" class=\"header fixed-top d-flex align-items-center\">\r\n");
      out.write("\t\t\t<div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("\t\t\t\t<a href=\"Main.jsp\" class=\"logo d-flex align-items-center text-decoration-none\">\r\n");
      out.write("\t\t\t\t\t<img class=\"logoImg1 d-none d-lg-block\" src=\"./img/logo-somosngr.svg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t<img class=\"logoImg2 d-block d-lg-none\" src=\"./img/logo-ngr.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t<span class=\"d-none d-lg-block\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<i class=\"ri-menu-line toggle-sidebar-btn\"></i>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Fin Logo -->\r\n");
      out.write("\t\t\t<!-- Input para Buscar jeje-->\r\n");
      out.write("\t\t\t<div class=\"search-bar\">\r\n");
      out.write("\t\t\t\t<form class=\"search-form d-flex align-items-center my-auto\" method=\"POST\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"query\" placeholder=\"Buscar\" title=\"Enter search keyword\" />\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" title=\"Buscar\"><i class=\"ri-search-line\"></i></button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Fin Buscar  -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav class=\"header-nav ms-auto\">\r\n");
      out.write("\t\t\t\t<ul class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item d-block d-lg-none\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link nav-icon search-bar-toggle p-0\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ri-search-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- Fin Buscar Icon-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link nav-icon p-0\" href=\"#\" data-bs-toggle=\"dropdown\" id=\"noti\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ri-notification-3-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge bg-primary badge-number\">2</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<!-- End Notification Icon -->\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow notificaciones\" aria-labelledby=\"noti\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<!-- Final notificación Dropdown Items -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- Final Notification Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link nav-icon p-0\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ri-chat-1-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"badge bg-success badge-number\">5</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<!-- Final mensajes Icon -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow messages\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<!-- Final Mensajes Dropdown Items -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!--Final Mensajes Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown pe-3\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link nav-profile d-flex align-items-center pe-0\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"./img/userImg.png\" alt=\"Profile\" class=\"rounded-circle\" />\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"d-none d-md-block dropdown-toggle ps-2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<!-- End Profile Iamge Icon -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow profile\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr class=\"dropdown-divider\" />\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item d-flex align-items-center\" href=\"ControladorPerfil?accion=perfil\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"ri-settings-2-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>My Perfil</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr class=\"dropdown-divider\" />\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item d-flex align-items-center\" href=\"ControladorPerfil?accion=perfil\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"ri-settings-2-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Configuración</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr class=\"dropdown-divider\" />\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item d-flex align-items-center\" href=\"ControladorPerfil?accion=perfil\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"ri-settings-2-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Ayuda?</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr class=\"dropdown-divider\" />\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item d-flex align-items-center\" href=\"ControladorUsuario?accion=Salir\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"ri-settings-2-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Salir</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<!-- Final Perfil Dropdown Items -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!--Final Profile Nav -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!-- Final Icons Navigation -->\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Final Header -->\r\n");
      out.write("\t\t<aside id=\"sidebar\" class=\"sidebar\">\r\n");
      out.write("\t\t\t<ul class=\"sidebar-nav\" id=\"sidebar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link\" href=\"Main.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"bi bi-grid\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span>Inicio</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- final Dashboard Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link collapsed\" data-bs-target=\"#employes-nav\" data-bs-toggle=\"collapse\" href=\"#\"> <i class=\"ri-contacts-fill\"></i><span>Empleado</span><i class=\"ri-arrow-down-s-line ms-auto\"></i> </a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"employes-nav\" class=\"nav-content collapse\" data-bs-parent=\"#sidebar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ControladorCrud?accion=registrarEmpleado\"> <i class=\"ri-group-fill\"></i><span>Agregar Nuevo Empleado</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ControladorCrud?accion=listarEmpleados\"> <i class=\"ri-group-fill\"></i><span>Listar Empleados</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- Final componentes Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link collapsed\" data-bs-target=\"#category-nav\" data-bs-toggle=\"collapse\" href=\"#\"> <i class=\"ri-stack-line\"></i><span>Categoria</span><i class=\"ri-arrow-down-s-line ms-auto\"></i> </a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"category-nav\" class=\"nav-content collapse\" data-bs-parent=\"#sidebar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ControladorCategoria?accion=registrarCategoria\"> <i class=\"bi bi-circle\"></i><span>Agregar nuevo Categoria</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ControladorCategoria?accion=listarCategorias\"> <i class=\"bi bi-circle\"></i><span>Listar Categorias</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- Final Formulario Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link collapsed\" data-bs-target=\"#provaider-nav\" data-bs-toggle=\"collapse\" href=\"#\"> <i class=\"ri-slideshow-line\"></i><span>Proveedor</span><i class=\"ri-arrow-down-s-line ms-auto\"></i> </a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"provaider-nav\" class=\"nav-content collapse\" data-bs-parent=\"#sidebar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ControladorProveedor?accion=registrarProveedor\"> <i class=\"bi bi-circle\"></i><span>Agregar nuevo Proveedor</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ControladorProveedor?accion=listarProveedores\"> <i class=\"bi bi-circle\"></i><span>Listar Proveedores</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- End Tables Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link collapsed\" data-bs-target=\"#inventory-nav\" data-bs-toggle=\"collapse\" href=\"#\"> <i class=\"ri-todo-line\"></i><span>Inventario</span><i class=\"ri-arrow-down-s-line ms-auto\"></i> </a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"inventory-nav\" class=\"nav-content collapse\" data-bs-parent=\"#sidebar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ControladorInventario?accion=registrarInventario\"> <i class=\"bi bi-circle\"></i><span>Agregar Inventario Nuevo</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ControladorInventario?accion=listarInventario\"> <i class=\"bi bi-circle\"></i><span>Listar Inventarios</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- End Charts Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link collapsed\" data-bs-target=\"#team-nav\" data-bs-toggle=\"collapse\" href=\"#\"> <i class=\"ri-book-open-line\"></i><span>Equipo</span><i class=\"ri-arrow-down-s-line ms-auto\"></i> </a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"team-nav\" class=\"nav-content collapse\" data-bs-parent=\"#sidebar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ControladorEquipo?accion=registrarEquipo\"> <i class=\"bi bi-circle\"></i><span>Agregar nuevo Equipo</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ControladorEquipo?accion=listarEquipos\"> <i class=\"bi bi-circle\"></i><span>Listar Equipos</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- Final iconos Nav -->\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link collapsed\" data-bs-target=\"#details-nav\" data-bs-toggle=\"collapse\" href=\"#\"> <i class=\"ri-numbers-line\"></i><span>Detalles</span><i class=\"ri-arrow-down-s-line ms-auto\"></i> </a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"details-nav\" class=\"nav-content collapse\" data-bs-parent=\"#sidebar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ControladorDetalles?accion=entradas\"> <i class=\"bi bi-circle\"></i><span>Entradas</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ControladorDetalles?accion=salidas\"> <i class=\"bi bi-circle\"></i><span>Salidas</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- Final iconos Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-heading\">Configuraciones</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link collapsed\" href=\"ControladorPerfil?accion=perfil\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"ri-file-chart-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span>Perfil</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- Final Profile Page Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link collapsed\" href=\"ControladorCrud?accion=empresa\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"ri-file-chart-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span>Empresa</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- End F.A.Q Page Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link collapsed\" href=\"ControladorCrud?accion=contacto\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"ri-file-chart-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span>Contacto</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- Final Contact Page Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link collapsed\" href=\"ControladorCrud?accion=registro\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"ri-file-chart-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span>Registro</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- Final Registro Page Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link collapsed\" href=\"ControladorCrud?accion=login\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"ri-file-chart-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span>Login</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- Final Login Page Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link collapsed\" href=\"ControladorCrud?accion=error\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"ri-file-chart-line\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span>Error 404</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Final Sidebar-->\r\n");
      out.write("\t\t<!-- ======= Contenido principal======= -->\r\n");
      out.write("\t\t<main id=\"main\" class=\"main main-listado\">\r\n");
      out.write("\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t<div class=\"container-xxl flex-grow-1 container-p-y\">\r\n");
      out.write("\t\t\t<h4 class=\"fw-bold py-3 mb-4\"><span class=\"text-muted fw-light\">Listado /</span> Proveedor</h4>\r\n");
      out.write("\t\t\t<div class=\"container-fluid py-4\"\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t<div class=\"data-table-list\">\r\n");
      out.write("\t\t\t\t<div class=\"basic-tb-hd\">\r\n");
      out.write("\t\t\t\t\t<h2>Todos los proveedores</h2>\r\n");
      out.write("\t\t\t\t\t<p class=\"text-xs text-secondary textDate\"><script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(\"Actualizado : \" + new Date());\r\n");
      out.write("\t\t\t\t\t\t\t\t</script></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t<table id=\"data-table-basic\" class=\"table table-striped dataTable\" role=\"grid\" aria-describedby=\"data-table-basic_info\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr role=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"sorting_asc th-title text-uppercase text-xs  font-weight-bold opacity-7 \" tabindex=\"0\" aria-controls=\"data-table-basic\" rowspan=\"1\" colspan=\"1\" aria-sort=\"ascending\" aria-label=\"Name: activate to sort column descending\" style=\"width: 190px;\">RUC</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"sorting th-title text-uppercase text-xs  font-weight-bold opacity-7 \" tabindex=\"0\" aria-controls=\"data-table-basic\" rowspan=\"1\" colspan=\"1\" aria-label=\"Position: activate to sort column ascending\" style=\"width: 292px;\">Razón Social</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"sorting th-title text-uppercase text-xs font-weight-bold opacity-7 \" tabindex=\"0\" aria-controls=\"data-table-basic\" rowspan=\"1\" colspan=\"1\" aria-label=\"Office: activate to sort column ascending\" style=\"width: 145px;\">Categoria</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"sorting th-title text-uppercase text-xs font-weight-bold opacity-7 \" tabindex=\"0\" aria-controls=\"data-table-basic\" rowspan=\"1\" colspan=\"1\" aria-label=\"Age: activate to sort column ascending\" style=\"width: 52px;\">Teléfono</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"sorting th-title text-uppercase text-xs font-weight-bold opacity-7 \" tabindex=\"0\" aria-controls=\"data-table-basic\" rowspan=\"1\" colspan=\"1\" aria-label=\"Start date: activate to sort column ascending\" style=\"width: 125px;\">Email</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"sorting th-title text-uppercase text-xs font-weight-bold opacity-7 \" tabindex=\"0\" aria-controls=\"data-table-basic\" rowspan=\"1\" colspan=\"1\" aria-label=\"Salary: activate to sort column ascending\" style=\"width: 116px;\">Tipo Solicitud</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"sorting th-title text-uppercase text-xs font-weight-bold opacity-7 \" tabindex=\"0\" aria-controls=\"data-table-basic\" rowspan=\"1\" colspan=\"1\" aria-label=\"action: activate to sort column ascending\" style=\"width: 50px;\">Actions</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr role=\"row\" class=\"even\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"sorting_1\">Marcial</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Senior Javascript Developer</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Igme</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>21</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2012/03/29</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$433,060</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"text-secondary text-xs font-weight-bold align-middle text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn p-0 hide-arrow btn-editList\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"ri-more-2-fill\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"dropdown-menu menu-dropdown-b\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\"><i class=\"ri-edit-line\"></i> Edit</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\"><i class=\"ri-delete-bin-line\"></i> Delete</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th rowspan=\"1\" colspan=\"1\" class=\"th-footer\">RUC</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th rowspan=\"1\" colspan=\"1\" class=\"th-footer\">R.S</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th rowspan=\"1\" colspan=\"1\" class=\"th-footer\">Categoria</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th rowspan=\"1\" colspan=\"1\" class=\"th-footer\">Telefono</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th rowspan=\"1\" colspan=\"1\" class=\"th-footer\">Email</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th rowspan=\"1\" colspan=\"1\" class=\"th-footer\">T.S</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th rowspan=\"1\" colspan=\"1\" class=\"th-footer\">Filtrar</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</main>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ======= Footer ======= -->\r\n");
      out.write("\r\n");
      out.write("\t\t<footer id=\"footer\" class=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"site-footer\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"./img/logo-ngr-white.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /.widget -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget socialContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Siguenos en:</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"social d-flex justify-content-start align-items-center px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a><i class=\"ri-linkedin-fill\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a><i class=\"ri-facebook-fill\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /.widget -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /.col-lg-3 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3 ml-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget text-start link-container-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"footer-subTitle\">Por categoría</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"list-unstyled float-left links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"links\" href=\"#\">Política de datos personales</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"links\" href=\"#\"> Encargados del tratamiento</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"links\" href=\"#\">Empresas y socios estratégicos</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"links\" href=\"#\">Derechos ARCO</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /.widget -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /.col-lg-3 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget text-start\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"footer-subTitle\">Contacto</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<address class=\"links\">Direccion no lo sé</address>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"list-unstyled links mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"links\" href=\"#\">99999999</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"links\" href=\"#\">2333333</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"links\" href=\"#\">ntg.gmail.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- /.widget -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /.col-lg-3 -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row mt-5\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\tCopyright &copy;\r\n");
      out.write("\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(new Date().getFullYear());\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t. Todos los Derechos Reservados. &mdash; Creado y desarrollado por <a href=\"#\">Igme</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- License information: igmreGroup -->\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /.container -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.site-footer -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t<!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a>\r\n");
      out.write("\t\t<!-- Sistema JS Files -->\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t<script src=\"./script/main.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.7.3/dist/sweetalert2.all.min.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"tr #deleteData\").click(function (e){\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tvar cod = $(this).parent().find(\"#codigo\").val();\t\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\t  title: '¿Estás seguro?',\r\n");
      out.write("\t\t\t\t\t  text: \"¡No podrás deshacer esto!\",\r\n");
      out.write("\t\t\t\t\t  icon: 'warning',\r\n");
      out.write("\t\t\t\t\t  showCancelButton: true,\r\n");
      out.write("\t\t\t\t\t  confirmButtonColor: '#3085d6',\r\n");
      out.write("\t\t\t\t\t  cancelButtonColor: '#d33',\r\n");
      out.write("\t\t\t\t\t  confirmButtonText: 'Si, Eliminar!'\r\n");
      out.write("\t\t\t\t\t}).then(function(result) {\r\n");
      out.write("\t\t\t\t\t  if (result.isConfirmed) {\r\n");
      out.write("\t\t\t\t\t\t  eliminar(cod);\r\n");
      out.write("\t\t\t\t\t    Swal.fire(\r\n");
      out.write("\t\t\t\t\t      '¡Borrado!',\r\n");
      out.write("\t\t\t\t\t      'El archivo ha sido borrado.',\r\n");
      out.write("\t\t\t\t\t      'success'\r\n");
      out.write("\t\t\t\t\t    )\r\n");
      out.write("\t\t\t\t\t    setTimeout(function(){\r\n");
      out.write("\t\t\t\t\t    \tparent.location.href = \"ControladorProveedor?accion=listarProveedores\"\r\n");
      out.write("\t\t\t\t\t    },1800);\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t})\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\tfunction eliminar (cod){\t\t\r\n");
      out.write("\t\t\t\tvar url = \"ControladorProveedor?accion=eliminarProveedor&cod=\" + cod;\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype: 'POST',\r\n");
      out.write("\t\t\t\t\turl: url,\r\n");
      out.write("\t\t\t\t\tasync: true,\r\n");
      out.write("\t\t\t\t\tsuccess: function(r){\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /ListadoProveedores.jsp(339,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("proveedor");
    // /ListadoProveedores.jsp(339,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/ListadoProveedores.jsp(339,6) '${listadoProv}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${listadoProv}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<tr role=\"row\" class=\"odd\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"sorting_1 text-secondary text-dark font-weight-bold \">");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"text-secondary text-dark  font-weight-bold\">");
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"text-secondary text-dark  font-weight-bold\">");
          if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"text-secondary text-dark font-weight-bold\">");
          if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"text-secondary text-dark font-weight-bold\">");
          if (_jspx_meth_c_005fout_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"text-secondary text-dark font-weight-bold\">");
          if (_jspx_meth_c_005fout_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"text-secondary text-dark font-weight-bold align-middle text-center\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"dropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn p-0 hide-arrow btn-editList\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"ri-more-2-fill\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</button>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"dropdown-menu menu-dropdown-b\" style=\"\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005furl_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\"><i class=\"ri-edit-line\"></i> Editar\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                                                   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"codigo\"  value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedor.idProveedor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a id=\"deleteData\" class=\"dropdown-item\" href=\"");
          if (_jspx_meth_c_005furl_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\"><i class=\"ri-delete-bin-line\"></i> Eliminar</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /ListadoProveedores.jsp(341,73) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedor.ruc}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /ListadoProveedores.jsp(342,63) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedor.razonSocial}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /ListadoProveedores.jsp(343,63) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedor.categoria}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /ListadoProveedores.jsp(344,62) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedor.telefono}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
    if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /ListadoProveedores.jsp(345,62) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedor.email}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
    if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /ListadoProveedores.jsp(346,62) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedor.tipoSolitud}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
    if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /ListadoProveedores.jsp(354,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("ControladorProveedor");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_eval_c_005furl_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_c_005furl_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_push_body_count_c_005fforEach_005f0[0]++;
        _jspx_th_c_005furl_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_c_005furl_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t      ");
        if (_jspx_meth_c_005fparam_005f0(_jspx_th_c_005furl_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t ");
        if (_jspx_meth_c_005fparam_005f1(_jspx_th_c_005furl_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t     ");
        int evalDoAfterBody = _jspx_th_c_005furl_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_c_005furl_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
        _jspx_push_body_count_c_005fforEach_005f0[0]--;
      }
    }
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f0 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    _jspx_th_c_005fparam_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f0);
    // /ListadoProveedores.jsp(355,21) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f0.setName("accion");
    // /ListadoProveedores.jsp(355,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f0.setValue("leerProveedor");
    int _jspx_eval_c_005fparam_005f0 = _jspx_th_c_005fparam_005f0.doStartTag();
    if (_jspx_th_c_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f1 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    _jspx_th_c_005fparam_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f0);
    // /ListadoProveedores.jsp(356,16) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f1.setName("codPro");
    // /ListadoProveedores.jsp(356,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f1.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedor.idProveedor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fparam_005f1 = _jspx_th_c_005fparam_005f1.doStartTag();
    if (_jspx_th_c_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /ListadoProveedores.jsp(361,62) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("ControladorProveedor");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_eval_c_005furl_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_c_005furl_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_push_body_count_c_005fforEach_005f0[0]++;
        _jspx_th_c_005furl_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_c_005furl_005f1.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fparam_005f2(_jspx_th_c_005furl_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write(" \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fparam_005f3(_jspx_th_c_005furl_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005furl_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_c_005furl_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
        _jspx_push_body_count_c_005fforEach_005f0[0]--;
      }
    }
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f2 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    _jspx_th_c_005fparam_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f1);
    // /ListadoProveedores.jsp(362,15) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f2.setName("accion");
    // /ListadoProveedores.jsp(362,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f2.setValue("eliminarProveedor");
    int _jspx_eval_c_005fparam_005f2 = _jspx_th_c_005fparam_005f2.doStartTag();
    if (_jspx_th_c_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f3 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    _jspx_th_c_005fparam_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fparam_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f1);
    // /ListadoProveedores.jsp(363,15) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f3.setName("cod");
    // /ListadoProveedores.jsp(363,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fparam_005f3.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${proveedor.idProveedor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fparam_005f3 = _jspx_th_c_005fparam_005f3.doStartTag();
    if (_jspx_th_c_005fparam_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f3);
    return false;
  }
}
